# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter : mysql2
  encoding: utf8
  pool    : 5
  timeout : 5000
  username: root
  password: OKAryo-8118
  socket  : /tmp/mysql.sock
  host    : localhost

development:
  adapter : mysql2
  database: my_database_development
  pool    : 5
  timeout : 5000
test:
  adapter : mysql2
  database: my_database_test
  pool    : 5
  timeout : 5000

production:
  <<: *default
  database: booklist_production
  pool: 5
  socket: /var/lib/mysql/mysql.sock
